[project]
name = "luma_demo"
version = "0.1.0"
description = "Complete Luma demonstration"
dependencies = [
    "path@..[fonts]",
]

[lint]
default = "warn"
dependencies = "allow"

[lint.rules]
unused-mut = "allow"
missing-public-docstring = "allow"
